/**
 * AFL award (trophy wall) helpers.
 *
 * The AFL hands out a set of distinct awards each season — the overall AFL
 * Championship, the legacy AFL Cup (2016–2017 only, before the conference
 * format), the two conference (AL/NL) titles, four division titles, the NIT
 * consolation crown, and the two all-play tier championships (Premier League /
 * D-League). Each has its own branded SVG badge under
 * public/assets/afl/awards/. Not every award exists in every era — the AFL Cup
 * predates the AL/NL split, so a season carries only the awards it actually
 * held.
 *
 * Award winners per season live in data/afl-fantasy/awards-history.json,
 * generated by scripts/compute-afl-awards.mjs. Keep the slug→badge mapping
 * here so every call site derives the path instead of hardcoding it (mirrors
 * getConferenceLogo in afl-conference.ts / getTierLogo in afl-tier.ts).
 */

import awardsHistory from '../../data/afl-fantasy/awards-history.json';

export type AwardSlug =
  | 'afl-championship'
  | 'afl-cup'
  | 'al-champion'
  | 'nl-champion'
  | 'al-north'
  | 'al-central'
  | 'al-south'
  | 'nl-east'
  | 'nl-west'
  | 'nl-pacific'
  | 'nit'
  | 'premier-league'
  | 'dleague-champion';

export type AwardCategory =
  | 'championship'
  | 'cup'
  | 'conference'
  | 'division'
  | 'consolation'
  | 'tier';

/**
 * Display tier for the trophy room. Awards are grouped into four labelled
 * sections in this order: Gold (AFL Championship / Cup / Premier League),
 * Conference Titles (AL/NL), Division Titles (the four), and Silver Titles
 * (D-League / NIT).
 */
export type AwardTier = 'gold' | 'conference' | 'division' | 'silver';

export interface AwardTierMeta {
  key: AwardTier;
  label: string;
}

/** Trophy-room sections, in display order. */
export const AWARD_TIERS: AwardTierMeta[] = [
  { key: 'gold', label: 'Championships' },
  { key: 'conference', label: 'Conference Titles' },
  { key: 'division', label: 'Division Titles' },
  { key: 'silver', label: 'Consolation Titles' },
];

export interface AwardType {
  slug: AwardSlug;
  /** Short display label for the badge. */
  label: string;
  /** Badge SVG filename (under public/assets/afl/awards/). */
  badge: string;
  category: AwardCategory;
  /** Trophy-room section this award is displayed under. */
  tier: AwardTier;
  /**
   * Whether wins expand to one year-stamped badge each (`true`) or collapse to
   * a single counted item (`false`). Every current award is `dated: true` — each
   * badge's art carries an editable year — so the collapsed path is vestigial,
   * kept only so the model can support a count-only award later.
   */
  dated?: boolean;
}

/**
 * Canonical, ordered list of every AFL award. Order is load-bearing: the
 * trophy room renders badges in this sequence, grouped by `tier` (gold →
 * conference → division → silver).
 */
export const AWARD_TYPES: AwardType[] = [
  { slug: 'afl-championship', label: 'AFL Champion', badge: 'afl-championship.svg', category: 'championship', tier: 'gold', dated: true },
  { slug: 'afl-cup', label: 'AFL Cup', badge: 'afl-cup.svg', category: 'cup', tier: 'gold', dated: true },
  { slug: 'premier-league', label: 'Premier League', badge: 'premier-league.svg', category: 'tier', tier: 'gold', dated: true },
  { slug: 'al-champion', label: 'AL Champion', badge: 'al-champion.svg', category: 'conference', tier: 'conference', dated: true },
  { slug: 'nl-champion', label: 'NL Champion', badge: 'nl-champion.svg', category: 'conference', tier: 'conference', dated: true },
  { slug: 'al-north', label: 'AL North', badge: 'al-north.svg', category: 'division', tier: 'division', dated: true },
  { slug: 'al-central', label: 'AL Central', badge: 'al-central.svg', category: 'division', tier: 'division', dated: true },
  { slug: 'al-south', label: 'AL South', badge: 'al-south.svg', category: 'division', tier: 'division', dated: true },
  { slug: 'nl-east', label: 'NL East', badge: 'nl-east.svg', category: 'division', tier: 'division', dated: true },
  { slug: 'nl-west', label: 'NL West', badge: 'nl-west.svg', category: 'division', tier: 'division', dated: true },
  { slug: 'nl-pacific', label: 'NL Pacific', badge: 'nl-pacific.svg', category: 'division', tier: 'division', dated: true },
  { slug: 'dleague-champion', label: 'D-League Champion', badge: 'dleague-champion.svg', category: 'tier', tier: 'silver', dated: true },
  { slug: 'nit', label: 'NIT Champion', badge: 'nit.svg', category: 'consolation', tier: 'silver', dated: true },
];

const BY_SLUG = new Map<AwardSlug, AwardType>(
  AWARD_TYPES.map((a) => [a.slug, a])
);

/** A single award winner for a given season. */
export interface AwardWinner {
  franchiseId: string | null;
  name: string | null;
  source: string;
}

export interface AwardSeason {
  year: number;
  awards: Partial<Record<AwardSlug, AwardWinner>>;
}

interface AwardsHistoryFile {
  seasons?: AwardSeason[];
}

const SEASONS: AwardSeason[] = (awardsHistory as AwardsHistoryFile).seasons ?? [];

/**
 * Resolve the branded award badge path (served from public/). Single source
 * of truth — call sites derive the path, never hardcode it.
 */
export function getAwardBadge(slug: AwardSlug): string {
  const type = BY_SLUG.get(slug);
  return `/assets/afl/awards/${type ? type.badge : `${slug}.svg`}`;
}

export function getAwardType(slug: AwardSlug): AwardType | undefined {
  return BY_SLUG.get(slug);
}

/** One award type annotated with the years a given franchise won it. */
export interface FranchiseAward extends AwardType {
  /** Years this franchise won the award, most recent first. Empty = locked. */
  years: number[];
  badgePath: string;
}

/**
 * Aggregate one franchise's award history into the full badge "locker".
 * Always returns every AwardType in taxonomy order; awards the franchise has
 * never won carry an empty `years` array (rendered as a locked slot).
 */
export function getFranchiseAwards(franchiseId: string): FranchiseAward[] {
  return AWARD_TYPES.map((type) => {
    const years: number[] = [];
    for (const season of SEASONS) {
      if (season.awards?.[type.slug]?.franchiseId === franchiseId) {
        years.push(season.year);
      }
    }
    years.sort((a, b) => b - a);
    return { ...type, years, badgePath: getAwardBadge(type.slug) };
  });
}

/** Total number of badges (award-years) a franchise has earned. */
export function countFranchiseBadges(franchiseId: string): number {
  return getFranchiseAwards(franchiseId).reduce(
    (sum, a) => sum + a.years.length,
    0
  );
}

/**
 * One physical trophy in a franchise's case. Dated (major) awards expand to one
 * item per winning year (`year` set); undated awards (divisions/conference)
 * collapse to a single item carrying all winning `years` + a count.
 */
export interface TrophyCaseItem {
  slug: AwardSlug;
  label: string;
  category: AwardCategory;
  tier: AwardTier;
  dated: boolean;
  badge: string;
  /** Single winning year — set only for dated awards. */
  year?: number;
  /** All winning years (desc). Length 1 for a dated item. Empty when locked. */
  years: number[];
  /** True for an unwon, greyed-out placeholder (active award not yet earned). */
  locked?: boolean;
}

/**
 * Build a franchise's trophy case: only awards actually won, in taxonomy order.
 * Dated awards (every current award) expand to one year-stamped badge per win,
 * most recent first; a non-dated award would collapse to a single counted item.
 * Returns [] for a franchise with no hardware.
 */
export function getFranchiseTrophyCase(franchiseId: string): TrophyCaseItem[] {
  const items: TrophyCaseItem[] = [];
  for (const type of AWARD_TYPES) {
    const years: number[] = [];
    for (const season of SEASONS) {
      if (season.awards?.[type.slug]?.franchiseId === franchiseId) {
        years.push(season.year);
      }
    }
    if (!years.length) continue;
    years.sort((a, b) => b - a);
    const base = {
      slug: type.slug,
      label: type.label,
      category: type.category,
      tier: type.tier,
      dated: !!type.dated,
      badge: type.badge,
    };
    if (type.dated) {
      for (const year of years) items.push({ ...base, year, years: [year] });
    } else {
      items.push({ ...base, years });
    }
  }
  return items;
}

/** A trophy-room section: one tier label plus the trophies that fall under it. */
export interface TrophyTierGroup {
  key: AwardTier;
  label: string;
  items: TrophyCaseItem[];
}

/**
 * A franchise's trophy case grouped into the four display tiers (Gold,
 * Conference, Division, Silver), in order. Empty tiers are omitted so a
 * franchise only shows sections it actually has hardware in.
 */
export function getFranchiseTrophyCaseByTier(franchiseId: string): TrophyTierGroup[] {
  const all = getFranchiseTrophyCase(franchiseId);
  return AWARD_TIERS.map(({ key, label }) => ({
    key,
    label,
    items: all.filter((t) => t.tier === key),
  })).filter((g) => g.items.length > 0);
}

/**
 * Active award types every current franchise competes for — shown as a
 * greyed-out locked placeholder when the franchise has never won them. Retired
 * awards (AFL Cup, AL Central, NL Pacific) are intentionally excluded: they only
 * appear when actually won. The team's own conference/division titles are added
 * per-franchise in getFranchiseTrophyRoom.
 */
const ALWAYS_ACTIVE: AwardSlug[] = [
  'afl-championship',
  'premier-league',
  'dleague-champion',
  'nit',
];

export interface TrophyRoomOpts {
  /** The franchise's current division slug, e.g. 'al-north'. */
  divisionSlug?: AwardSlug;
  /** The franchise's current conference slug, e.g. 'al-champion'. */
  conferenceSlug?: AwardSlug;
}

/**
 * A franchise's trophy room: every won trophy (year-stamped) PLUS greyed-out
 * locked placeholders for the active awards it has never won — the universal
 * majors (AFL Championship, Premier League, D-League, NIT) and its own
 * conference + division title. Grouped into the four tiers, in order; earned
 * items first within each tier, then locked.
 */
export function getFranchiseTrophyRoom(
  franchiseId: string,
  opts: TrophyRoomOpts = {}
): TrophyTierGroup[] {
  const earned = getFranchiseTrophyCase(franchiseId);
  const earnedSlugs = new Set(earned.map((t) => t.slug));

  const lockable = new Set<AwardSlug>(ALWAYS_ACTIVE);
  if (opts.conferenceSlug) lockable.add(opts.conferenceSlug);
  if (opts.divisionSlug) lockable.add(opts.divisionSlug);

  const locked: TrophyCaseItem[] = [];
  for (const slug of lockable) {
    if (earnedSlugs.has(slug)) continue;
    const type = BY_SLUG.get(slug);
    if (!type) continue;
    locked.push({
      slug: type.slug,
      label: type.label,
      category: type.category,
      tier: type.tier,
      dated: !!type.dated,
      badge: type.badge,
      years: [],
      locked: true,
    });
  }

  const all = [...earned, ...locked];
  return AWARD_TIERS.map(({ key, label }) => ({
    key,
    label,
    items: all.filter((t) => t.tier === key),
  })).filter((g) => g.items.length > 0);
}

/**
 * The six TITLE TYPES a franchise can win, in prestige order. Each type maps to
 * one or more award slugs — Conference and Division collapse their multiple
 * slugs (any conference / any division title counts), the other four are 1:1.
 * Retired award slugs (AFL Cup) are intentionally not a type of their own.
 */
export type TitleTypeKey =
  | 'afl'
  | 'premier'
  | 'conference'
  | 'division'
  | 'dleague'
  | 'nit';

interface TitleTypeDef {
  key: TitleTypeKey;
  label: string;
  slugs: AwardSlug[];
}

export const TITLE_TYPES: TitleTypeDef[] = [
  { key: 'afl', label: 'AFL', slugs: ['afl-championship'] },
  { key: 'premier', label: 'Premier', slugs: ['premier-league'] },
  { key: 'conference', label: 'Conference', slugs: ['al-champion', 'nl-champion'] },
  {
    key: 'division',
    label: 'Division',
    slugs: ['al-north', 'al-central', 'al-south', 'nl-east', 'nl-west', 'nl-pacific'],
  },
  { key: 'dleague', label: 'D-League', slugs: ['dleague-champion'] },
  { key: 'nit', label: 'NIT', slugs: ['nit'] },
];

/** One title type, annotated with whether/when a franchise has won it. */
export interface TitleTypeProgress {
  key: TitleTypeKey;
  label: string;
  /** Award slugs that satisfy this type. */
  slugs: AwardSlug[];
  /** True when the franchise has won at least one title of this type. */
  won: boolean;
  /** Winning years across this type's slugs, most recent first. */
  years: number[];
}

export interface FranchiseTitleProgress {
  /** All six title types, in prestige order. */
  types: TitleTypeProgress[];
  /** How many distinct types have been won (0–6). */
  wonCount: number;
  /** Total number of title types (6). */
  total: number;
}

/**
 * How many of the six title TYPES a franchise has won at least one of. Powers
 * the trophy-wall progress bar — `wonCount`/`total` is the headline number, and
 * each `types[]` entry carries the per-type win years (for the segment tooltip).
 */
export function getFranchiseTitleProgress(franchiseId: string): FranchiseTitleProgress {
  const types: TitleTypeProgress[] = TITLE_TYPES.map((t) => {
    const years: number[] = [];
    for (const season of SEASONS) {
      // A season can credit a franchise multiple slugs of one type only in
      // pathological data; first match per season is enough.
      if (t.slugs.some((slug) => season.awards?.[slug]?.franchiseId === franchiseId)) {
        years.push(season.year);
      }
    }
    years.sort((a, b) => b - a);
    return { key: t.key, label: t.label, slugs: [...t.slugs], won: years.length > 0, years };
  });
  const wonCount = types.filter((t) => t.won).length;
  return { types, wonCount, total: types.length };
}

/**
 * "Grand Slam" status — has a franchise won at least one of *every* title type?
 * Derived from getFranchiseTitleProgress so it stays in lockstep with the
 * progress bar (completed ⇔ the bar reads 6/6).
 *
 * The completion `year` is the season the franchise won its *final missing*
 * title type — the latest of each type's earliest win. That's the moment the
 * set was first complete. Reserved for a later phase (a "Grand Slam" badge).
 */
export interface GrandSlamStatus {
  /** True once every title type has been won at least once. */
  completed: boolean;
  /** Season the slam was completed (the final missing type's first win). */
  year?: number;
  /** Title types still unwon (empty once completed). */
  missingTypes: TitleTypeKey[];
}

export function getFranchiseGrandSlam(franchiseId: string): GrandSlamStatus {
  const { types } = getFranchiseTitleProgress(franchiseId);
  const missingTypes = types.filter((t) => !t.won).map((t) => t.key);
  if (missingTypes.length > 0) {
    return { completed: false, missingTypes };
  }
  // Each type's earliest win; the slam completes on the latest of those.
  const year = Math.max(...types.map((t) => Math.min(...t.years)));
  return { completed: true, year, missingTypes: [] };
}
