/**
 * AFL award (trophy wall) helpers.
 *
 * The AFL hands out a set of distinct awards each season — the overall AFL
 * Championship, the legacy AFL Cup (2016–2017 only, before the conference
 * format), the two conference (AL/NL) titles, four division titles, the NIT
 * consolation crown, and the two all-play tier championships (Premier League /
 * D-League). Each has its own branded SVG badge under
 * public/assets/afl/awards/. Not every award exists in every era — the AFL Cup
 * predates the AL/NL split, so a season carries only the awards it actually
 * held.
 *
 * Award winners per season live in data/afl-fantasy/awards-history.json,
 * generated by scripts/compute-afl-awards.mjs. Keep the slug→badge mapping
 * here so every call site derives the path instead of hardcoding it (mirrors
 * getConferenceLogo in afl-conference.ts / getTierLogo in afl-tier.ts).
 */

import awardsHistory from '../../data/afl-fantasy/awards-history.json';

export type AwardSlug =
  | 'afl-championship'
  | 'afl-cup'
  | 'al-champion'
  | 'nl-champion'
  | 'al-north'
  | 'al-south'
  | 'nl-east'
  | 'nl-west'
  | 'nit'
  | 'premier-league'
  | 'dleague-champion';

export type AwardCategory =
  | 'championship'
  | 'cup'
  | 'conference'
  | 'division'
  | 'consolation'
  | 'tier';

export interface AwardType {
  slug: AwardSlug;
  /** Short display label for the badge. */
  label: string;
  /** Badge SVG filename (under public/assets/afl/awards/). */
  badge: string;
  category: AwardCategory;
  /**
   * True if the badge art carries an editable year arc (`#yearArc` textPath) —
   * the "major" trophies. Dated badges render one stamped instance per win in
   * the trophy case; undated badges (divisions, conference) render once with a
   * win count.
   */
  dated?: boolean;
}

/**
 * Canonical, ordered list of every AFL award. Order is load-bearing: the
 * trophy wall renders badges in this sequence (championship → conference →
 * division → consolation → tier) so the locker layout is stable.
 */
export const AWARD_TYPES: AwardType[] = [
  { slug: 'afl-championship', label: 'AFL Champion', badge: 'afl-championship.svg', category: 'championship', dated: true },
  { slug: 'afl-cup', label: 'AFL Cup', badge: 'afl-cup.svg', category: 'cup', dated: true },
  { slug: 'al-champion', label: 'AL Champion', badge: 'al-champion.svg', category: 'conference', dated: true },
  { slug: 'nl-champion', label: 'NL Champion', badge: 'nl-champion.svg', category: 'conference', dated: true },
  { slug: 'al-north', label: 'AL North', badge: 'al-north.svg', category: 'division', dated: true },
  { slug: 'al-south', label: 'AL South', badge: 'al-south.svg', category: 'division', dated: true },
  { slug: 'nl-east', label: 'NL East', badge: 'nl-east.svg', category: 'division', dated: true },
  { slug: 'nl-west', label: 'NL West', badge: 'nl-west.svg', category: 'division', dated: true },
  { slug: 'nit', label: 'NIT Champion', badge: 'nit.svg', category: 'consolation', dated: true },
  { slug: 'premier-league', label: 'Premier League', badge: 'premier-league.svg', category: 'tier', dated: true },
  { slug: 'dleague-champion', label: 'D-League Champion', badge: 'dleague-champion.svg', category: 'tier', dated: true },
];

const BY_SLUG = new Map<AwardSlug, AwardType>(
  AWARD_TYPES.map((a) => [a.slug, a])
);

/** A single award winner for a given season. */
export interface AwardWinner {
  franchiseId: string | null;
  name: string | null;
  source: string;
}

export interface AwardSeason {
  year: number;
  awards: Partial<Record<AwardSlug, AwardWinner>>;
}

interface AwardsHistoryFile {
  seasons?: AwardSeason[];
}

const SEASONS: AwardSeason[] = (awardsHistory as AwardsHistoryFile).seasons ?? [];

/**
 * Resolve the branded award badge path (served from public/). Single source
 * of truth — call sites derive the path, never hardcode it.
 */
export function getAwardBadge(slug: AwardSlug): string {
  const type = BY_SLUG.get(slug);
  return `/assets/afl/awards/${type ? type.badge : `${slug}.svg`}`;
}

export function getAwardType(slug: AwardSlug): AwardType | undefined {
  return BY_SLUG.get(slug);
}

/** One award type annotated with the years a given franchise won it. */
export interface FranchiseAward extends AwardType {
  /** Years this franchise won the award, most recent first. Empty = locked. */
  years: number[];
  badgePath: string;
}

/**
 * Aggregate one franchise's award history into the full badge "locker".
 * Always returns every AwardType in taxonomy order; awards the franchise has
 * never won carry an empty `years` array (rendered as a locked slot).
 */
export function getFranchiseAwards(franchiseId: string): FranchiseAward[] {
  return AWARD_TYPES.map((type) => {
    const years: number[] = [];
    for (const season of SEASONS) {
      if (season.awards?.[type.slug]?.franchiseId === franchiseId) {
        years.push(season.year);
      }
    }
    years.sort((a, b) => b - a);
    return { ...type, years, badgePath: getAwardBadge(type.slug) };
  });
}

/** Total number of badges (award-years) a franchise has earned. */
export function countFranchiseBadges(franchiseId: string): number {
  return getFranchiseAwards(franchiseId).reduce(
    (sum, a) => sum + a.years.length,
    0
  );
}

/**
 * One physical trophy in a franchise's case. Dated (major) awards expand to one
 * item per winning year (`year` set); undated awards (divisions/conference)
 * collapse to a single item carrying all winning `years` + a count.
 */
export interface TrophyCaseItem {
  slug: AwardSlug;
  label: string;
  category: AwardCategory;
  dated: boolean;
  badge: string;
  /** Single winning year — set only for dated awards. */
  year?: number;
  /** All winning years (desc). Length 1 for a dated item. */
  years: number[];
}

/**
 * Build a franchise's trophy case: only awards actually won, in taxonomy order,
 * with dated majors expanded to one year-stamped badge per win (most recent
 * first) and undated awards shown once with their win count. Returns [] for a
 * franchise with no hardware.
 */
export function getFranchiseTrophyCase(franchiseId: string): TrophyCaseItem[] {
  const items: TrophyCaseItem[] = [];
  for (const type of AWARD_TYPES) {
    const years: number[] = [];
    for (const season of SEASONS) {
      if (season.awards?.[type.slug]?.franchiseId === franchiseId) {
        years.push(season.year);
      }
    }
    if (!years.length) continue;
    years.sort((a, b) => b - a);
    const base = {
      slug: type.slug,
      label: type.label,
      category: type.category,
      dated: !!type.dated,
      badge: type.badge,
    };
    if (type.dated) {
      for (const year of years) items.push({ ...base, year, years: [year] });
    } else {
      items.push({ ...base, years });
    }
  }
  return items;
}
