import PeckingOrderIssue from '../../src/components/shared/PeckingOrderIssue.astro';
import { themeModes, leagueModes } from '../../.storybook/modes';
import issue from '../fixtures/pecking-order-issue.json';
import aflIssue from '../fixtures/pecking-order-issue-afl.json';

/**
 * A full Pecking Order issue — power rankings, awards and standings, rendered
 * for both leagues from one component.
 *
 * The fixture is a FROZEN COPY of a real published issue
 * (data/theleague/pecking-order/2025-16.json), not an import of it. That file
 * is regenerated by a weekly cron, so importing it would repaint these
 * snapshots on a schedule and produce diffs that mean nothing. Copying it once
 * keeps the render truthful and the baseline stable.
 *
 * Its 16 rankings, 4 divisions and 5 populated awards exercise far more of the
 * component than a hand-built stub would, including the award cards that only
 * appear in some weeks.
 */
export default {
  title: 'Shared/PeckingOrderIssue',
  component: PeckingOrderIssue,
  parameters: {
    layout: 'fullscreen',
    // themeModes, NOT allModes: TheLeague and Afl are separate stories
    // driven by the `league` prop, so the league mode would re-snapshot an
    // axis the args already cover.
    chromatic: { modes: themeModes },
  },
};

export const TheLeague = {
  args: { issue, league: 'theleague', variant: 'live' },
};

/**
 * The AFL rendering the same component — a real AFL issue, not TheLeague's
 * data wearing an AFL skin.
 *
 * This uses its OWN frozen fixture (data/afl-fantasy/pecking-order/2025-13),
 * because `league` drives franchise lookups: feeding TheLeague's fixture with
 * `league: 'afl'` resolves TheLeague's franchise ids against the AFL config
 * and produces a hybrid that exists nowhere. With the right fixture this
 * genuinely exercises the 24-team field against TheLeague's 16 — the field
 * size lives in the data, the skin in CSS, and both differ correctly here.
 */
export const Afl = {
  // 'afl', NOT 'afl-fantasy'. This repo has TWO slug vocabularies:
  // `LeagueSlug` (types/nav) is 'theleague' | 'afl' | 'bb1' and is what this
  // component takes; `CanonicalLeagueSlug` (config/leagues) is 'theleague' |
  // 'afl-fantasy' | 'best-ball-1' and is what QuickLinks takes. Passing the
  // wrong one does not error — CONFIGS[league] falls back to TheLeague, so the
  // story silently rendered TheLeague's franchises and gave zero AFL coverage.
  args: { issue: aflIssue, league: 'afl', variant: 'live' },
  // AFL content needs the AFL skin. The default themeModes pins
  // data-league="theleague", which would render AFL data under TheLeague's
  // palette — the exact mismatch this story exists to catch.
  parameters: { chromatic: { modes: leagueModes } },
};

/**
 * The preseason "here's the format" rendering. Drops the headline to h2 and
 * hides the publish date — a Week 16 issue stamped with today's date reads as
 * fresh news when it isn't. Structurally different, and only reachable in
 * production for a few weeks a year.
 */
export const SampleVariant = {
  args: { issue, league: 'theleague', variant: 'sample' },
};

/**
 * An issue with no awards at all — the shape of an early week, before there is
 * anything to hand out.
 *
 * Note the section wrapper and its heading render regardless; only the cards
 * are conditional. So this pins "awards heading with nothing under it", which
 * is worth seeing precisely because it may not be what anyone intended.
 */
export const NoAwards = {
  args: {
    issue: {
      ...issue,
      awards: {
        statOfWeek: null,
        benchBlunder: null,
        tradeOfWeek: null,
        cutOfShame: null,
        heaterOfWeek: null,
        coolerOfWeek: null,
        matchupOfWeek: null,
      },
    },
    league: 'theleague',
    variant: 'live',
  },
};
