import PeckingOrderIssue from '../../src/components/shared/PeckingOrderIssue.astro';
import { themeModes } from '../../.storybook/modes';
import issue from '../fixtures/pecking-order-issue.json';

/**
 * A full Pecking Order issue — power rankings, awards and standings, rendered
 * for both leagues from one component.
 *
 * The fixture is a FROZEN COPY of a real published issue
 * (data/theleague/pecking-order/2025-16.json), not an import of it. That file
 * is regenerated by a weekly cron, so importing it would repaint these
 * snapshots on a schedule and produce diffs that mean nothing. Copying it once
 * keeps the render truthful and the baseline stable.
 *
 * Its 16 rankings, 4 divisions and 5 populated awards exercise far more of the
 * component than a hand-built stub would, including the award cards that only
 * appear in some weeks.
 */
export default {
  title: 'Shared/PeckingOrderIssue',
  component: PeckingOrderIssue,
  parameters: {
    layout: 'fullscreen',
    // themeModes, NOT allModes: TheLeague and Afl are separate stories
    // driven by the `league` prop, so the league mode would re-snapshot an
    // axis the args already cover.
    chromatic: { modes: themeModes },
  },
};

export const TheLeague = {
  args: { issue, league: 'theleague', variant: 'live' },
};

/**
 * The AFL renders the same component with a 24-team field against
 * TheLeague's 16. Here it is the same fixture under the AFL skin, which is
 * what the theme × league matrix is for — the field-size difference lives in
 * the data, the skin difference lives in CSS, and only one of them should
 * change between these two stories.
 */
export const Afl = {
  args: { issue, league: 'afl-fantasy', variant: 'live' },
};

/**
 * The preseason "here's the format" rendering. Drops the headline to h2 and
 * hides the publish date — a Week 16 issue stamped with today's date reads as
 * fresh news when it isn't. Structurally different, and only reachable in
 * production for a few weeks a year.
 */
export const SampleVariant = {
  args: { issue, league: 'theleague', variant: 'sample' },
};

/**
 * An issue with no awards at all. The awards block is built conditionally, so
 * this is a genuinely different render — and it is the shape of an early-week
 * issue before there is anything to award.
 */
export const NoAwards = {
  args: {
    issue: {
      ...issue,
      awards: {
        statOfWeek: null,
        benchBlunder: null,
        tradeOfWeek: null,
        cutOfShame: null,
        heaterOfWeek: null,
        coolerOfWeek: null,
        matchupOfWeek: null,
      },
    },
    league: 'theleague',
    variant: 'live',
  },
};
