#!/usr/bin/env node
/**
 * Generate a new league site from a launch spec — the "Launch" half of the
 * League Launcher (step 3 of the new-league roadmap).
 *
 *   node scripts/new-league.mjs --spec spec.json            # write everything
 *   node scripts/new-league.mjs --spec spec.json --dry-run  # print the plan
 *   node scripts/new-league.mjs --spec '{"mflId":…}' --offline
 *
 * `--spec` is a path or inline JSON:
 *
 *   {
 *     "mflId": "12345",                 MFL league id
 *     "slug": "smith",                  lowercase letters/digits; also the nav slug
 *     "name": "Smith Family League",
 *     "shortName": "Smith",             optional
 *     "mflHost": "www4x.myfantasyleague.com",  the league's MFL server
 *     "archetype": "standard-redraft",  src/config/league-archetypes.mjs
 *     "features": { …every catalog key: boolean },
 *     "duplicatePlayers": false,        optional (MFL playerLimitUnit ≠ LEAGUE)
 *     "adminFranchiseIds": ["0001"],    optional
 *     "theme": "archies"                optional; a file in src/themes/
 *   }
 *
 * What it writes (all derived from the spec and the registry, nothing per
 * league is hand-kept here):
 *   - the registry entry in src/config/leagues-data.mjs;
 *   - data/<slug>/<slug>.config.json (empty teams; filled by branding);
 *   - data seeds the pages import directly (news feed, free-agents shape);
 *   - one thin route per page the ticked features entitle, generated from
 *     Archie's routes (the package-league template) with the slug swapped;
 *   - page-directory entries and a nav section for those routes;
 *   - its config in chromatic.yml (the scheduled jobs read the registry —
 *     scripts/lib/league-jobs.mjs — so no workflow lists the league);
 *   - the regenerated theme stylesheet (it selects every league).
 * Then, unless `--offline`: fetches the league's MFL feeds, suggests its
 * branding, and computes its free-agent board.
 *
 * Pages are Archie's set gated by feature: the shared pages that already
 * work for any league. The richer TheLeague/AFL pages arrive as they are
 * unforked (roadmap item 6). Archie's own competition (The Gauntlet, the MAD
 * standings) and its theme previews are never copied.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { LEAGUES } from '../src/config/leagues-data.mjs';
import { ARCHETYPES } from '../src/config/league-archetypes.mjs';
import { FEATURE_KEYS } from '../src/config/league-feature-catalog.mjs';
import { packageRoutesFor } from '../src/config/package-league-routes.mjs';
import { SLUG_RE, specErrors as baseSpecErrors } from '../src/config/launch-spec.mjs';
import { applyChanges, syncPlan } from './lib/package-kit.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const TEMPLATE = 'archies';
export const PLACEHOLDER_LOGO = '/assets/logos/league-placeholder.svg';


// ── Spec ─────────────────────────────────────────────────────────────────────

/**
 * Every problem with a spec: the shared checks (src/config/launch-spec.mjs,
 * the same ones the Launcher page runs) plus this checkout's filesystem.
 */
export function specErrors(spec) {
  const errors = baseSpecErrors(spec);
  if (errors.length) return errors;
  if (spec.theme !== undefined && !fs.existsSync(path.join(ROOT, 'src/themes', `${spec.theme}.json`))) {
    errors.push(`theme ${spec.theme} has no src/themes/${spec.theme}.json`);
  }
  if (fs.existsSync(path.join(ROOT, 'src/pages', spec.slug))) errors.push(`src/pages/${spec.slug} already exists`);
  return errors;
}

/** The routes a spec's features entitle (src/config/package-league-routes.mjs). */
export const routesFor = packageRoutesFor;

// ── Registry entry ───────────────────────────────────────────────────────────

/** A JS literal in the registry's house style: single-quoted strings. */
const q = (v) =>
  JSON.stringify(v).replace(/"((?:[^"\\]|\\.)*)"/g, (_, body) => {
    const raw = JSON.parse(`"${body}"`);
    return raw.includes("'") ? JSON.stringify(raw) : `'${raw}'`;
  }).replace(/,(?=\S)/g, ', ');

export function registryEntry(spec, today = new Date().toISOString().slice(0, 10)) {
  const preset = ARCHETYPES[spec.archetype];
  const example = preset.example ? LEAGUES[preset.example] : null;
  const rankingSources = (example ?? LEAGUES[TEMPLATE]).defaultRankingSources ?? [];
  const f = spec.features;
  const lines = [
    `  ${spec.slug}: {`,
    `    /** Generated by scripts/new-league.mjs on ${today} (${spec.archetype}). */`,
    `    id: ${q(String(spec.mflId))},`,
    `    slug: ${q(spec.slug)},`,
    `    navSlug: /** @type {const} */ (${q(spec.slug)}),`,
    `    theme: ${q(spec.theme ?? TEMPLATE)},`,
    `    archetype: ${q(spec.archetype)},`,
    `    adminFranchiseIds: ${q(spec.adminFranchiseIds ?? [])},`,
    `    name: ${q(spec.name)},`,
    ...(spec.shortName ? [`    shortName: ${q(spec.shortName)},`] : []),
    `    /** Placeholder mark until the league's own art is set (both cuts, per the registry rule). */`,
    `    logo: { light: ${q(PLACEHOLDER_LOGO)}, dark: ${q(PLACEHOLDER_LOGO)} },`,
    `    mflHost: ${q(spec.mflHost)},`,
    `    dataPath: ${q(`data/${spec.slug}`)},`,
    `    configPath: ${q(`data/${spec.slug}/${spec.slug}.config.json`)},`,
    `    schefterFeedPath: ${q(`data/${spec.slug}/schefter-feed.json`)},`,
    `    domains: [],`,
    `    stagingDomains: [],`,
    `    advertiseOnSharedHost: false,`,
    `    optInNav: true,`,
    `    pageKit: 'package',`,
    `    ownersPoll: { enabled: false, slots: 0, closeWeekday: 4, closeHourPT: 16 },`,
    ...(f.powerRankings ? [`    peckingOrder: { topN: 25 },`] : []),
    ...(spec.duplicatePlayers ? [`    duplicatePlayers: true,`] : []),
    `    officialClock: {`,
    `      id: 'PT',`,
    `      zone: 'America/Los_Angeles',`,
    `      label: 'PT',`,
    `      name: "The league's clock (Pacific)",`,
    `      equivalents: ['America/Vancouver', 'America/Tijuana'],`,
    `    },`,
    `    tradeDeadline: null,`,
    `    features: {`,
    ...FEATURE_KEYS.map((k) => `      ${k}: ${Boolean(f[k])},`),
    `    },`,
    `    defaultRankingSources: ${q(rankingSources)},`,
    `    /** No weekly Schefter articles until chosen: each type links pages a package league may not have. */`,
    `    articleTypes: [],`,
    `  },`,
  ];
  return lines.join('\n') + '\n';
}

/** Insert `entry` as the last member of `export const LEAGUES = { … };`. */
export function insertRegistryEntry(source, entry) {
  const start = source.indexOf('export const LEAGUES = {');
  if (start < 0) throw new Error('LEAGUES object not found in leagues-data.mjs');
  const end = source.indexOf('\n};\n', start);
  if (end < 0) throw new Error('end of LEAGUES object not found');
  return `${source.slice(0, end + 1)}${entry}${source.slice(end + 1)}`;
}

/**
 * Set an existing entry's `features` values in the registry source, keeping
 * every comment and the key order — only the `true`/`false` literals change.
 * A key the block lacks is appended before its closing brace.
 *
 * Plain string matching, never a RegExp built from the slug or a key: both can
 * arrive from the command line, and the slug and keys are checked against
 * their fixed shapes first anyway.
 */
export function setRegistryFeatures(source, slug, features) {
  if (!SLUG_RE.test(String(slug))) throw new Error(`not a league slug: ${slug}`);
  for (const key of Object.keys(features)) {
    if (!FEATURE_KEYS.includes(key)) throw new Error(`not a feature key: ${key}`);
  }
  const heads = [`\n  ${slug}: {\n`, `\n  '${slug}': {\n`];
  const start = Math.max(...heads.map((h) => source.indexOf(h)));
  if (start < 0) throw new Error(`registry entry ${slug} not found`);
  const open = source.indexOf('\n    features: {\n', start);
  const next = source.slice(start + 1).search(/\n  [\w'-]+: \{\n/);
  if (open < 0 || (next >= 0 && open > start + 1 + next)) throw new Error(`${slug} has no features block`);
  const close = source.indexOf('\n    },', open);
  const lines = source.slice(open, close).split('\n');
  for (const [key, on] of Object.entries(features)) {
    const at = lines.findIndex((l) => l === `      ${key}: true,` || l === `      ${key}: false,`);
    if (at >= 0) lines[at] = `      ${key}: ${Boolean(on)},`;
    else lines.push(`      ${key}: ${Boolean(on)},`);
  }
  return source.slice(0, open) + lines.join('\n') + source.slice(close);
}

// ── Plan ─────────────────────────────────────────────────────────────────────

/**
 * Every file the launch writes, as { path, content } with repo-relative paths.
 * Pure apart from reading the template files and the current repo files.
 */
export function planLaunch(spec) {
  const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
  const files = [];
  const year = new Date().getFullYear();

  // Registry.
  const registryPath = 'src/config/leagues-data.mjs';
  files.push({ path: registryPath, content: insertRegistryEntry(read(registryPath), registryEntry(spec)) });

  // Data seeds the pages import directly.
  const dataDir = `data/${spec.slug}`;
  files.push({
    path: `${dataDir}/${spec.slug}.config.json`,
    content: `${JSON.stringify(
      {
        $comment: `${spec.name}: teams, divisions and branding. Seeded empty by scripts/new-league.mjs; filled by scripts/suggest-league-branding.mjs --league ${spec.slug} --write, then edited by hand or the branding editor.`,
        leagueId: String(spec.mflId),
        name: spec.name,
        structure: 'divisions',
        divisions: [],
        teams: [],
      },
      null,
      2,
    )}\n`,
  });
  files.push({
    path: `${dataDir}/schefter-feed.json`,
    content: `${JSON.stringify({ $comment: `${spec.name} news feed. Starts empty.`, posts: [] }, null, 2)}\n`,
  });
  files.push({
    path: `${dataDir}/derived/free-agents.json`,
    content: `${JSON.stringify(
      {
        generatedForYear: year,
        statsSeasonYear: year,
        mflHost: spec.mflHost,
        conferences: { ids: [], names: {}, franchiseConferences: {} },
        rosterFranchiseCount: 0,
        hasProjected: false,
        hasSeasonPts: false,
        hasAdp: false,
        defaultSort: 'projected',
        defaultDir: 'desc',
        faCounts: {},
        positions: [],
        nflTeamsList: [],
        topFa: null,
        players: [],
      },
      null,
      2,
    )}\n`,
  });

  // Pages, site-search entries and the nav section: the package kit
  // (scripts/lib/package-kit.mjs), the same sync that keeps every package
  // league in line with its features afterwards.
  const changes = syncPlan(spec);
  files.push(...changes);
  const routes = routesFor(spec.features);
  const added = JSON.parse(changes.find((c) => c.path === 'src/data/page-directory.json').content).filter(
    (e) => e.path === `/${spec.slug}` || e.path.startsWith(`/${spec.slug}/`),
  );

  // Chromatic: every league's config renders into a story (the shared
  // league-config loader globs them all), so each one is a trigger path.
  const chromaticPath = '.github/workflows/chromatic.yml';
  const chromatic = read(chromaticPath);
  const configLine = /^(\s+)- 'data\/archies\/archies\.config\.json'\n/gm;
  if (!configLine.test(chromatic)) throw new Error('chromatic.yml config path anchor not found');
  files.push({
    path: chromaticPath,
    content: chromatic.replace(configLine, (line, indent) => `${line}${indent}- 'data/${spec.slug}/${spec.slug}.config.json'\n`),
  });

  return { files, routes, directoryEntries: added.length };
}

// ── CLI ──────────────────────────────────────────────────────────────────────

function readSpec(arg) {
  if (!arg) throw new Error('--spec <file|json> is required');
  const raw = arg.trim().startsWith('{') ? arg : fs.readFileSync(arg, 'utf8');
  return JSON.parse(raw);
}

function run(cmd, args, env = {}) {
  execFileSync(cmd, args, { cwd: ROOT, stdio: 'inherit', env: { ...process.env, ...env } });
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const argv = process.argv.slice(2);
  const opt = (name) => (argv.includes(name) ? argv[argv.indexOf(name) + 1] : undefined);
  const dryRun = argv.includes('--dry-run');
  const offline = argv.includes('--offline');

  const spec = readSpec(opt('--spec') ?? process.env.LAUNCH_SPEC);
  const errors = specErrors(spec);
  if (errors.length) {
    console.error(`Spec rejected:\n  - ${errors.join('\n  - ')}`);
    process.exit(1);
  }

  const plan = planLaunch(spec);
  console.log(`Launching ${spec.name} (${spec.slug}, MFL ${spec.mflId}) as ${spec.archetype}`);
  console.log(`  ${plan.routes.length} pages, ${plan.directoryEntries} page-directory entries`);
  for (const f of plan.files) console.log(`  ${dryRun ? 'would ' : ''}${f.content === null ? 'delete' : 'write'} ${f.path}`);
  if (dryRun) process.exit(0);

  applyChanges(plan.files);

  // The theme stylesheet selects every league by its data-league; regenerate it.
  run(process.execPath, ['scripts/generate-league-themes.mjs']);

  if (!offline) {
    const env = { MFL_LEAGUE_ID: String(spec.mflId), MFL_LEAGUE_SLUG: spec.slug };
    run(process.execPath, ['scripts/fetch-mfl-feeds.mjs'], env);
    run(process.execPath, ['scripts/suggest-league-branding.mjs', '--league', spec.slug, '--write']);
    run(process.execPath, ['scripts/compute-free-agents.mjs', '--league', spec.slug]);
  }

  console.log(`\nDone. Still by hand:
  - Replace the placeholder logo (registry \`logo\`, both cuts) with the league's art.
  - Review data/${spec.slug}/${spec.slug}.config.json (team names, colours, divisions).${
    spec.features.pushNotifications
      ? `
  - Push art: until the registry has \`pushArt\` (scripts/generate-notification-icons.mjs, from the
    league's own favicon), its alerts show the shared site mark.`
      : ''
  }
  - Optional: a custom domain (registry \`domains\`, Vercel, DNS).`);
}
