/**
 * The /redraft demo (docs/plans/custom-site-demo.md, phase 4): a fictional
 * 12-team best-ball league in the Best Ball slot, with its startup draft
 * already run.
 *
 * Best ball is draft-only — no lineups, no waivers — so the league IS its
 * draft. The real slot's draft lives in PartyKit (a live external service);
 * the demo never touches it. Instead this writes a completed draft session
 * that src/utils/best-ball-draft.ts serves on a demo deployment, and prospects
 * run their own mock drafts against bots.
 *
 * Only NFL facts are read: the player list and MFL's redraft ADP.
 */

import { createRng } from './rng.mjs';
import { lighten } from './franchises.mjs';
import { withArt } from './art-mix.mjs';
import { crestSvg } from './crests.mjs';

const RAW = [
  ['0001', 'Stack City Sharks', 'Sharks', 'SCS', '#0b6e99', '#ffd166'],
  ['0002', 'Upside Hunters', 'Hunters', 'UPH', '#6d28d9', '#fde68a'],
  ['0003', 'Zero RB Zealots', 'Zealots', 'ZRZ', '#b91c1c', '#fecaca'],
  ['0004', 'Late Round QBs', 'Late QBs', 'LRQ', '#065f46', '#a7f3d0'],
  ['0005', 'Ceiling Chasers', 'Chasers', 'CEC', '#1e3a8a', '#bfdbfe'],
  ['0006', 'Hero RB Heroes', 'Heroes', 'HRB', '#9a3412', '#fed7aa'],
  ['0007', 'Spike Week Sprinters', 'Sprinters', 'SWS', '#0f766e', '#99f6e4'],
  ['0008', 'Robust Rovers', 'Rovers', 'RBR', '#374151', '#e5e7eb'],
  ['0009', 'Tight End Titans', 'Titans', 'TET', '#7c2d12', '#fcd34d'],
  ['0010', 'Correlation Crew', 'Crew', 'COC', '#be185d', '#fbcfe8'],
  ['0011', 'Bye Week Rustlers', 'Rustlers', 'BWR', '#4d7c0f', '#d9f99d'],
  ['0012', 'Playoff Stackers', 'Stackers', 'PLS', '#1d4ed8', '#e0e7ff'],
];

export const BESTBALL_FRANCHISES = withArt('redraft', RAW.map(([id, name, nameShort, abbrev, colorPrimary, colorSecondary]) => ({
  id,
  name,
  nameShort,
  abbrev,
  colorPrimary,
  colorSecondary,
  colorPrimaryDark: lighten(colorPrimary, 0.25),
})));

export const BESTBALL_LEAGUE_NAME = 'The Demo Best Ball League';
/** The real slot drafts 25 rounds (`BEST_BALL_TOTAL_ROUNDS`), and its pages say so. */
export const BESTBALL_ROUNDS = 25;

/** Best-ball roster build: enough at each spot to field a lineup every week. */
const POSITION_CAP = { QB: 3, RB: 9, WR: 10, TE: 3, PK: 0, Def: 0 };

/** `data/best-ball-1/bb1.config.json`, fictional — same shape as the real one. */
export function bestBallConfig({ leagueId, loaderLines }) {
  return {
    $comment: 'Demo best-ball league (fictional), generated by scripts/demo. See docs/plans/custom-site-demo.md.',
    leagueId,
    name: BESTBALL_LEAGUE_NAME,
    loaderLines,
    teams: BESTBALL_FRANCHISES.map((f) => ({
      franchiseId: f.id,
      name: f.name,
      nameMedium: f.nameShort,
      nameShort: f.nameShort,
      abbrev: f.abbrev,
      colorPrimary: f.colorPrimary,
      colorSecondary: f.colorSecondary,
      // The draft room, board and rosters draw this crest (its `_dark` cut
      // sits beside it); the real league has none, so those pages skip it.
      icon: bestBallIcon(f),
    })),
  };
}

const bestBallKey = (f) => f.name.toLowerCase().replace(/[^a-z0-9]+/g, '_');
const bestBallIcon = (f, dark = false) => `/assets/bestball/icons/${bestBallKey(f)}${dark ? '_dark' : ''}.svg`;

export function bestBallAssets(generatedAt) {
  const entry = (relativePath) => ({ type: 'icons', filename: relativePath.split('/').pop(), relativePath, extension: '.svg' });
  return {
    $comment: 'Demo best-ball league asset registry (fictional).',
    generatedAt,
    teams: BESTBALL_FRANCHISES.map((f) => {
      const key = bestBallKey(f);
      return { key, slug: key, id: f.id, name: f.name, category: 'active', aliases: [], assets: { icons: [entry(bestBallIcon(f))] } };
    }),
  };
}

/**
 * The redraft demo's crests (public/ path → SVG): the real best-ball league
 * has no art yet, so the demo shows what a league with it looks like — real
 * art on the art-mix teams, a generated shield on the rest.
 */
export function bestBallArtFiles() {
  const files = new Map();
  for (const f of BESTBALL_FRANCHISES) {
    files.set(bestBallIcon(f).slice(1), crestSvg(f));
    files.set(bestBallIcon(f, true).slice(1), crestSvg(f, { dark: true }));
  }
  return files;
}

/**
 * A completed 25-round snake draft, in the MockDraftSession shape the
 * best-ball pages read. Each pick takes the best available player by redraft
 * ADP, with noise, respecting position caps — a plausible room, not a perfect
 * one.
 *
 * @param {object} args
 * @param {Map<string, {id,name,position}>} args.players  NFL player identities
 * @param {{id:string, averagePick:string}[]} args.adp     MFL redraft ADP rows
 * @param {Map<string, number>} [args.depth]  last season's points, for the pool past ADP's end
 * @param {string} args.leagueId
 * @param {number} args.leagueYear
 * @param {string} args.seed
 * @param {number} args.draftStart  unix seconds
 */
export function bestBallDraft({ players, adp, depth = new Map(), leagueId, leagueYear, seed, draftStart }) {
  const rng = createRng(seed);
  const order = rng.shuffle(BESTBALL_FRANCHISES.map((f) => f.id));
  const n = order.length;
  const ranked = adp
    .filter((row) => players.has(row.id) && POSITION_CAP[players.get(row.id).position] > 0)
    .map((row) => ({ id: row.id, pos: players.get(row.id).position, adp: Number(row.averagePick) }))
    .sort((a, b) => a.adp - b.adp);
  // MFL's ADP list is shorter than a 300-pick draft; the tail comes from last
  // season's points (`depth`: player id → points), after every ADP player.
  const inAdp = new Set(ranked.map((p) => p.id));
  const tail = [...depth.entries()]
    .filter(([id]) => !inAdp.has(id) && players.has(id) && POSITION_CAP[players.get(id).position] > 0)
    .sort((a, b) => b[1] - a[1])
    .map(([id], i) => ({ id, pos: players.get(id).position, adp: 1000 + i }));
  const pool = [...ranked, ...tail];

  const counts = new Map(order.map((fid) => [fid, {}]));
  const taken = new Set();
  const draftOrder = [];
  const picks = [];
  let at = draftStart;
  for (let round = 1; round <= BESTBALL_ROUNDS; round++) {
    const roundOrder = round % 2 === 1 ? order : [...order].reverse();
    roundOrder.forEach((fid, i) => {
      draftOrder.push(fid);
      const mine = counts.get(fid);
      const window = pool.filter((p) => !taken.has(p.id) && (mine[p.pos] ?? 0) < POSITION_CAP[p.pos]).slice(0, 6);
      if (!window.length) return;
      // Mostly the best available; sometimes a reach within the next few.
      const choice = window[Math.min(window.length - 1, Math.floor(Math.abs(rng.noise(1.2))))];
      taken.add(choice.id);
      mine[choice.pos] = (mine[choice.pos] ?? 0) + 1;
      at += rng.int(20, 90);
      picks.push({
        overallPickNumber: (round - 1) * n + i + 1,
        round,
        pickInRound: i + 1,
        franchiseId: fid,
        playerId: choice.id,
        pickedAt: new Date(at * 1000).toISOString(),
        isAutoPick: false,
      });
    });
  }

  return {
    id: `demo-bb1-official-${leagueYear}`,
    leagueId,
    leagueYear,
    createdBy: order[0],
    createdAt: new Date(draftStart * 1000).toISOString(),
    status: 'completed',
    draftOrder,
    picksPerRound: n,
    totalRounds: BESTBALL_ROUNDS,
    currentPickIndex: draftOrder.length,
    timerSeconds: 60,
    picks,
    participants: [],
    useRealOrder: false,
    official: true,
  };
}

/** Best ball's lineup: the league sets it, every week, from the roster's best scores. */
const BEST_BALL_LINEUP = { QB: 1, RB: 2, WR: 3, TE: 1, FLEX: 1 };
const FLEX = ['RB', 'WR', 'TE'];
const REGULAR_SEASON_WEEKS = 14;

/** The optimal lineup for one team-week: the players the league would start. */
function bestLineup(roster, weekScores, positionOf) {
  const byScore = [...roster].sort((a, b) => (weekScores.get(b) ?? 0) - (weekScores.get(a) ?? 0));
  const starters = [];
  const counts = {};
  for (const pid of byScore) {
    const pos = positionOf(pid);
    if ((counts[pos] ?? 0) < (BEST_BALL_LINEUP[pos] ?? 0)) {
      counts[pos] = (counts[pos] ?? 0) + 1;
      starters.push(pid);
    }
  }
  for (const pid of byScore) {
    if (starters.filter((p) => FLEX.includes(positionOf(p))).length >= BEST_BALL_LINEUP.RB + BEST_BALL_LINEUP.WR + BEST_BALL_LINEUP.TE + BEST_BALL_LINEUP.FLEX) break;
    if (!starters.includes(pid) && FLEX.includes(positionOf(pid))) starters.push(pid);
  }
  const score = starters.reduce((s, pid) => s + (weekScores.get(pid) ?? 0), 0);
  const two = (n) => (Math.round(n * 100) / 100).toFixed(2);
  return {
    score: Math.round(score * 100) / 100,
    optPts: Math.round(score * 100) / 100,
    starters,
    nonstarters: roster.filter((pid) => !starters.includes(pid)),
    optimal: starters,
    players: roster.map((pid) => ({ id: pid, score: two(weekScores.get(pid) ?? 0), status: starters.includes(pid) ? 'starter' : 'nonstarter' })),
  };
}

/** A 12-team round robin (circle method), repeated to fill the regular season. */
function roundRobin(ids, weeks) {
  const rest = ids.slice(1);
  const rounds = [];
  for (let r = 0; r < ids.length - 1; r++) {
    const ring = [ids[0], ...rest];
    const games = [];
    for (let i = 0; i < ids.length / 2; i++) {
      const a = ring[i];
      const b = ring[ring.length - 1 - i];
      games.push(r % 2 ? [a, b] : [b, a]);
    }
    rounds.push(games);
    rest.unshift(rest.pop());
  }
  return Array.from({ length: weeks }, (_, w) => rounds[w % rounds.length]);
}

/**
 * The redraft demo's season so far, in the shape the shared MFL feed writers
 * take (mfl-feeds.mjs): rosters from the demo's own draft, a round-robin
 * schedule, every played week scored as best ball does (each team's optimal
 * lineup from the real NFL scores), and the week in progress — so the live
 * scoring board has something to show.
 *
 * @param {{ draft: { picks: Array<{ franchiseId: string, playerId: string }> }, facts: any, currentWeek: number }} args
 */
export function bestBallSeason({ draft, facts, currentWeek }) {
  const ids = BESTBALL_FRANCHISES.map((f) => f.id);
  const rosterIds = new Map(ids.map((fid) => [fid, []]));
  for (const p of draft.picks) rosterIds.get(p.franchiseId)?.push(p.playerId);
  const positionOf = (pid) => facts.players.get(pid)?.position;
  const schedule = roundRobin(ids, REGULAR_SEASON_WEEKS);
  const lastWeek = Math.min(currentWeek, REGULAR_SEASON_WEEKS);

  const weekly = [];
  for (let week = 1; week <= lastWeek; week++) {
    const scores = facts.scores.get(week) ?? new Map();
    const lineups = new Map(ids.map((fid) => [fid, bestLineup(rosterIds.get(fid), scores, positionOf)]));
    weekly.push({
      week,
      regularSeason: true,
      games: schedule[week - 1].map(([home, away]) => [lineups.get(home), lineups.get(away), home, away]),
    });
  }

  // The week being played: the teams whose NFL game is done have points; the
  // rest are still to play (the same test simulate.mjs's liveWeek uses).
  let inProgress = null;
  const liveWeek = lastWeek + 1;
  const partial = facts.scores.get(liveWeek);
  if (liveWeek <= REGULAR_SEASON_WEEKS && partial) {
    const teamOf = (pid) => facts.players.get(pid)?.team;
    const teamsPlayed = new Set([...partial].filter(([, s]) => s !== 0).map(([pid]) => teamOf(pid)).filter(Boolean));
    if (teamsPlayed.size) {
      const played = (pid) => teamsPlayed.has(teamOf(pid));
      const live = new Map([...partial].filter(([pid]) => played(pid)));
      const lineups = new Map(ids.map((fid) => [fid, bestLineup(rosterIds.get(fid), live, positionOf)]));
      for (const lineup of lineups.values()) {
        for (const p of lineup.players) p.gameSecondsRemaining = played(p.id) ? '0' : '3600';
      }
      inProgress = { week: liveWeek, games: schedule[liveWeek - 1].map(([home, away]) => [lineups.get(home), lineups.get(away), home, away]) };
    }
  }

  const rosters = new Map(
    ids.map((fid) => [fid, new Map(rosterIds.get(fid).map((pid) => [pid, { status: 'ROSTER', salary: 0, contractYear: 1 }]))]),
  );
  return { rosters, schedule, weekly, inProgress, lastWeek };
}
