/**
 * The /keeper demo (docs/plans/custom-site-demo.md, phase 4): a fictional
 * 12-team keeper league — no salary cap, no contracts; every offseason each
 * team keeps its best seven and re-drafts the rest — in the demo-only `keeper`
 * slot, rendered by the AFL's pages (components/afl-family).
 *
 * One conference, two divisions: the AFL-family pages render whichever
 * conferences a league has, and one conference is also what makes the
 * free-agent pool a single shared one (no duplicate-player split).
 *
 * Nothing here may resemble a real franchise or owner — the post-build leak
 * scan fails the demo build if one does.
 */

import { lighten } from './franchises.mjs';
import { bannerSvg, crestSvg, leagueMarkSvg } from './crests.mjs';

export const KEEPER_LEAGUE_NAME = 'The Keeper League';
export const KEEPER_DIVISIONS = ['Lakes', 'Ridge'];
export const KEEPER_CONFERENCE = { code: '00', name: 'The Keeper League', short: 'KL' };

/** id, name, short name, abbrev, owner, division index, primary, secondary. */
const RAW = [
  ['0001', 'Northshore Lumberjacks', 'Lumberjacks', 'NSL', 'Wren Calloway', 0, '#355e3b', '#e8d8b0'],
  ['0002', 'Pinecrest Owls', 'Owls', 'PCO', 'Dmitri Hale', 0, '#4b3f72', '#f2c14e'],
  ['0003', 'Stillwater Otters', 'Otters', 'SWO', 'Jo Ramsdell', 0, '#1f6f8b', '#d9eef2'],
  ['0004', 'Birchwood Beavers', 'Beavers', 'BWB', 'Cal Petrakis', 0, '#8c5a2b', '#f4e1c1'],
  ['0005', 'Loon Lake Loons', 'Loons', 'LLL', 'Maren Sato', 0, '#1b1f3b', '#9fb4c7'],
  ['0006', 'Cedar Point Moose', 'Moose', 'CPM', 'Rafe Donnelly', 0, '#6b4226', '#c9b79c'],
  ['0007', 'Granite Peak Goats', 'Goats', 'GPG', 'Tess Aldana', 1, '#5c6770', '#f5f5f5'],
  ['0008', 'Timberline Wolves', 'Wolves', 'TLW', 'Baxter Quinlan', 1, '#2e3a46', '#b8c4cf'],
  ['0009', 'Summit Ridge Hawks', 'Hawks', 'SRH', 'Noor Haddad', 1, '#a23b2a', '#f0d9a8'],
  ['0010', 'Aspen Hollow Elk', 'Elk', 'AHE', 'Lyle Varga', 1, '#7a6a2f', '#efe6c8'],
  ['0011', 'Switchback Marmots', 'Marmots', 'SBM', 'Ines Barlow', 1, '#9b6b3d', '#2b2b2b'],
  ['0012', 'Cloudcap Condors', 'Condors', 'CCC', 'Ozzie Fairbanks', 1, '#3d5a80', '#ee6c4d'],
];

const ASSET_ROOT = '/assets/keeper';

export const KEEPER_FRANCHISES = RAW.map(([id, name, nameShort, abbrev, owner, divisionIndex, colorPrimary, colorSecondary]) => {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  return {
    id,
    name,
    nameShort,
    abbrev,
    owner,
    ownerFirst: owner.split(' ')[0],
    slug,
    divisionIndex,
    division: KEEPER_DIVISIONS[divisionIndex],
    colorPrimary,
    colorSecondary,
    colorPrimaryDark: lighten(colorPrimary, 0.25),
    colorSecondaryDark: lighten(colorSecondary, 0.6),
  };
});

function assetPaths(f) {
  return {
    icon: `${ASSET_ROOT}/icons/${f.slug}.svg`,
    iconDark: `${ASSET_ROOT}/icons/${f.slug}_dark.svg`,
    banner: `${ASSET_ROOT}/banners/${f.slug}.svg`,
  };
}

/** `data/keeper/keeper.config.json` — the AFL config's shape, one conference. */
export function keeperConfig({ leagueId }) {
  return {
    $comment: 'Demo keeper league (fictional), generated by scripts/demo. See docs/plans/custom-site-demo.md.',
    leagueId,
    name: KEEPER_LEAGUE_NAME,
    loaderLines: ['Counting keepers…', 'Sorting the seven you cannot live without…'],
    teams: KEEPER_FRANCHISES.map((f) => ({
      franchiseId: f.id,
      name: f.name,
      nameMedium: f.name,
      nameShort: f.nameShort,
      abbrev: f.abbrev,
      aliases: [],
      conference: KEEPER_CONFERENCE.code,
      division: f.division,
      tier: '',
      colorPrimary: f.colorPrimary,
      colorSecondary: f.colorSecondary,
      loaderQuips: [`${f.nameShort} are weighing their seventh keeper…`],
      ...assetPaths(f),
    })),
    conferences: [
      {
        name: KEEPER_CONFERENCE.name,
        short: KEEPER_CONFERENCE.short,
        code: KEEPER_CONFERENCE.code,
        divisions: KEEPER_DIVISIONS,
        divisionNames: Object.fromEntries(KEEPER_DIVISIONS.map((d) => [d, d])),
        draftKind: 'email',
      },
    ],
    divisions: KEEPER_DIVISIONS,
    divisionToConference: Object.fromEntries(KEEPER_DIVISIONS.map((d) => [d, KEEPER_CONFERENCE.code])),
    keepers: 7,
    structure: 'one-conference',
  };
}

/** The keeper league's public art: crests, banners and the league mark. */
export function keeperArtFiles() {
  const files = new Map();
  const strip = (p) => p.replace(/^\//, '');
  for (const f of KEEPER_FRANCHISES) {
    const p = assetPaths(f);
    files.set(strip(p.icon), crestSvg(f));
    files.set(strip(p.iconDark), crestSvg(f, { dark: true }));
    files.set(strip(p.banner), bannerSvg(f));
  }
  files.set('assets/logos/keeper-logo.svg', leagueMarkSvg(KEEPER_LEAGUE_NAME));
  files.set('assets/logos/keeper-logo-dark.svg', leagueMarkSvg(KEEPER_LEAGUE_NAME));
  return files;
}

/**
 * The keeper league's league.json: the dynasty feed's shape with a keeper
 * league's settings — no salaries or contracts, seven keepers, one conference.
 */
export function keeperLeagueFeed(base) {
  const league = { ...base.league };
  league.keeperType = 'keeper';
  league.usesSalaries = 'NO';
  league.usesContractYear = 'NO';
  league.maxKeepers = '7';
  league.minKeepers = '0';
  league.taxiSquad = '0';
  league.currentWaiverType = 'WAIVERS_FCFS';
  for (const k of ['salaryCapAmount', 'auctionStartAmount', 'bbidMinimum', 'bbidIncrement', 'bbidConditional', 'bbidTiebreaker', 'minBid', 'bidIncrement', 'auction_kind']) {
    delete league[k];
  }
  league.draft_kind = 'email';
  league.loadRosters = 'email_draft';
  league.draftPlayerPool = 'Both';
  league.conferences = { count: '1', conference: [{ name: KEEPER_CONFERENCE.name, id: KEEPER_CONFERENCE.code }] };
  const divisions = base.league.divisions.division.map((d) => ({ ...d, conference: KEEPER_CONFERENCE.code }));
  league.divisions = { count: String(divisions.length), division: divisions };
  return { ...base, league };
}
